default: &default
  adapter:  mysql2
  encoding: utf8mb4
  host:     <%= ENV.fetch('DB_HOST') %>
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
  pool:     <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') %>

test:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') %>_test

production:
  <<: *default
  database: <%= ENV.fetch('DB_NAME') %>
  username: <%= ENV.fetch('DB_USERNAME') %>
  password: <%= ENV.fetch('DB_PASSWORD') %>
